// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package carrierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarrierServiceClient is the client API for CarrierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarrierServiceClient interface {
	CreateCarrier(ctx context.Context, in *CreateCarrierRequest, opts ...grpc.CallOption) (*CreateCarrierResponse, error)
}

type carrierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarrierServiceClient(cc grpc.ClientConnInterface) CarrierServiceClient {
	return &carrierServiceClient{cc}
}

func (c *carrierServiceClient) CreateCarrier(ctx context.Context, in *CreateCarrierRequest, opts ...grpc.CallOption) (*CreateCarrierResponse, error) {
	out := new(CreateCarrierResponse)
	err := c.cc.Invoke(ctx, "/carrierpb.CarrierService/CreateCarrier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarrierServiceServer is the server API for CarrierService service.
// All implementations must embed UnimplementedCarrierServiceServer
// for forward compatibility
type CarrierServiceServer interface {
	CreateCarrier(context.Context, *CreateCarrierRequest) (*CreateCarrierResponse, error)
	mustEmbedUnimplementedCarrierServiceServer()
}

// UnimplementedCarrierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCarrierServiceServer struct {
}

func (UnimplementedCarrierServiceServer) CreateCarrier(context.Context, *CreateCarrierRequest) (*CreateCarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCarrier not implemented")
}
func (UnimplementedCarrierServiceServer) mustEmbedUnimplementedCarrierServiceServer() {}

// UnsafeCarrierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarrierServiceServer will
// result in compilation errors.
type UnsafeCarrierServiceServer interface {
	mustEmbedUnimplementedCarrierServiceServer()
}

func RegisterCarrierServiceServer(s grpc.ServiceRegistrar, srv CarrierServiceServer) {
	s.RegisterService(&CarrierService_ServiceDesc, srv)
}

func _CarrierService_CreateCarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarrierServiceServer).CreateCarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/carrierpb.CarrierService/CreateCarrier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarrierServiceServer).CreateCarrier(ctx, req.(*CreateCarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarrierService_ServiceDesc is the grpc.ServiceDesc for CarrierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarrierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "carrierpb.CarrierService",
	HandlerType: (*CarrierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCarrier",
			Handler:    _CarrierService_CreateCarrier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/carrierpb/carrier.proto",
}
