// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/carrierpb/carrier.proto

package carrierpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Carrier struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CarrierCode          string   `protobuf:"bytes,2,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	CarrierName          string   `protobuf:"bytes,3,opt,name=carrier_name,json=carrierName,proto3" json:"carrier_name,omitempty"`
	CarrierAddress       string   `protobuf:"bytes,4,opt,name=carrier_address,json=carrierAddress,proto3" json:"carrier_address,omitempty"`
	CarrierEmail         string   `protobuf:"bytes,5,opt,name=carrier_email,json=carrierEmail,proto3" json:"carrier_email,omitempty"`
	CarrierPhone         string   `protobuf:"bytes,6,opt,name=carrier_phone,json=carrierPhone,proto3" json:"carrier_phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Carrier) Reset()         { *m = Carrier{} }
func (m *Carrier) String() string { return proto.CompactTextString(m) }
func (*Carrier) ProtoMessage()    {}
func (*Carrier) Descriptor() ([]byte, []int) {
	return fileDescriptor_939817f64c9bebe8, []int{0}
}

func (m *Carrier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carrier.Unmarshal(m, b)
}
func (m *Carrier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carrier.Marshal(b, m, deterministic)
}
func (m *Carrier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carrier.Merge(m, src)
}
func (m *Carrier) XXX_Size() int {
	return xxx_messageInfo_Carrier.Size(m)
}
func (m *Carrier) XXX_DiscardUnknown() {
	xxx_messageInfo_Carrier.DiscardUnknown(m)
}

var xxx_messageInfo_Carrier proto.InternalMessageInfo

func (m *Carrier) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Carrier) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *Carrier) GetCarrierName() string {
	if m != nil {
		return m.CarrierName
	}
	return ""
}

func (m *Carrier) GetCarrierAddress() string {
	if m != nil {
		return m.CarrierAddress
	}
	return ""
}

func (m *Carrier) GetCarrierEmail() string {
	if m != nil {
		return m.CarrierEmail
	}
	return ""
}

func (m *Carrier) GetCarrierPhone() string {
	if m != nil {
		return m.CarrierPhone
	}
	return ""
}

type CreateCarrierRequest struct {
	Carrier              *Carrier `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCarrierRequest) Reset()         { *m = CreateCarrierRequest{} }
func (m *CreateCarrierRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCarrierRequest) ProtoMessage()    {}
func (*CreateCarrierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_939817f64c9bebe8, []int{1}
}

func (m *CreateCarrierRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCarrierRequest.Unmarshal(m, b)
}
func (m *CreateCarrierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCarrierRequest.Marshal(b, m, deterministic)
}
func (m *CreateCarrierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCarrierRequest.Merge(m, src)
}
func (m *CreateCarrierRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCarrierRequest.Size(m)
}
func (m *CreateCarrierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCarrierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCarrierRequest proto.InternalMessageInfo

func (m *CreateCarrierRequest) GetCarrier() *Carrier {
	if m != nil {
		return m.Carrier
	}
	return nil
}

type CreateCarrierResponse struct {
	Carrier              *Carrier `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCarrierResponse) Reset()         { *m = CreateCarrierResponse{} }
func (m *CreateCarrierResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCarrierResponse) ProtoMessage()    {}
func (*CreateCarrierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_939817f64c9bebe8, []int{2}
}

func (m *CreateCarrierResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCarrierResponse.Unmarshal(m, b)
}
func (m *CreateCarrierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCarrierResponse.Marshal(b, m, deterministic)
}
func (m *CreateCarrierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCarrierResponse.Merge(m, src)
}
func (m *CreateCarrierResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCarrierResponse.Size(m)
}
func (m *CreateCarrierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCarrierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCarrierResponse proto.InternalMessageInfo

func (m *CreateCarrierResponse) GetCarrier() *Carrier {
	if m != nil {
		return m.Carrier
	}
	return nil
}

func init() {
	proto.RegisterType((*Carrier)(nil), "carrierpb.Carrier")
	proto.RegisterType((*CreateCarrierRequest)(nil), "carrierpb.CreateCarrierRequest")
	proto.RegisterType((*CreateCarrierResponse)(nil), "carrierpb.CreateCarrierResponse")
}

func init() { proto.RegisterFile("api/v1/carrierpb/carrier.proto", fileDescriptor_939817f64c9bebe8) }

var fileDescriptor_939817f64c9bebe8 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd1, 0x41, 0x4f, 0x83, 0x30,
	0x14, 0x07, 0xf0, 0x80, 0x6e, 0xcb, 0xde, 0x1c, 0x26, 0x2f, 0x9a, 0x34, 0x8b, 0x51, 0xc4, 0x83,
	0x3b, 0x18, 0x16, 0xe7, 0xd1, 0x93, 0xe2, 0xae, 0xc6, 0xe0, 0xcd, 0x8b, 0xe9, 0xe8, 0x4b, 0x6c,
	0x22, 0x14, 0x5b, 0xdc, 0x07, 0xf5, 0x13, 0x99, 0x41, 0x4b, 0x60, 0xd1, 0xc3, 0x6e, 0xe5, 0xcf,
	0x8f, 0xc7, 0x7b, 0x7d, 0x70, 0xce, 0x4b, 0xb9, 0xd8, 0xdc, 0x2e, 0x32, 0xae, 0xb5, 0x24, 0x5d,
	0xae, 0xdd, 0x29, 0x2e, 0xb5, 0xaa, 0x14, 0x8e, 0xdb, 0x17, 0xd1, 0x8f, 0x07, 0xa3, 0xa4, 0x79,
	0xc2, 0x00, 0x7c, 0x29, 0x98, 0x17, 0x7a, 0xf3, 0x41, 0xea, 0x4b, 0x81, 0x97, 0x70, 0x64, 0xe1,
	0x7b, 0xa6, 0x04, 0x31, 0x3f, 0xf4, 0xe6, 0xe3, 0x74, 0x62, 0xb3, 0x44, 0x09, 0xea, 0x92, 0x82,
	0xe7, 0xc4, 0x0e, 0x7a, 0xe4, 0x99, 0xe7, 0x84, 0xd7, 0x70, 0xec, 0x08, 0x17, 0x42, 0x93, 0x31,
	0xec, 0xb0, 0x56, 0x81, 0x8d, 0x1f, 0x9a, 0x14, 0xaf, 0x60, 0xea, 0x20, 0xe5, 0x5c, 0x7e, 0xb2,
	0x41, 0xcd, 0xdc, 0x0f, 0x56, 0xdb, 0xac, 0x8b, 0xca, 0x0f, 0x55, 0x10, 0x1b, 0xf6, 0xd0, 0xcb,
	0x36, 0x8b, 0x9e, 0xe0, 0x24, 0xd1, 0xc4, 0x2b, 0xb2, 0x93, 0xa5, 0xf4, 0xf5, 0x4d, 0xa6, 0xc2,
	0x1b, 0x18, 0x59, 0x57, 0x4f, 0x39, 0x59, 0x62, 0xdc, 0xde, 0x44, 0xec, 0xac, 0x23, 0xd1, 0x0a,
	0x4e, 0x77, 0xaa, 0x98, 0x52, 0x15, 0x86, 0xf6, 0x2b, 0xb3, 0x14, 0x10, 0xd8, 0xec, 0x95, 0xf4,
	0x46, 0x66, 0x84, 0x29, 0x4c, 0x7b, 0x85, 0xf1, 0xa2, 0xfb, 0xfd, 0x1f, 0x8d, 0xcf, 0xc2, 0xff,
	0x41, 0xd3, 0xd3, 0xe3, 0xd9, 0xdb, 0x6c, 0x77, 0xe9, 0xf7, 0xed, 0x69, 0x3d, 0xac, 0xf7, 0x7e,
	0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x10, 0x9b, 0x16, 0x19, 0x02, 0x00, 0x00,
}
