// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/customerpb/customer.proto

package customerpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerCode         string   `protobuf:"bytes,2,opt,name=customer_code,json=customerCode,proto3" json:"customer_code,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerAddress      string   `protobuf:"bytes,4,opt,name=customer_address,json=customerAddress,proto3" json:"customer_address,omitempty"`
	CustomerEmail        string   `protobuf:"bytes,5,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerPhone        string   `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_212f321a2ac7b5a3, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetCustomerCode() string {
	if m != nil {
		return m.CustomerCode
	}
	return ""
}

func (m *Customer) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Customer) GetCustomerAddress() string {
	if m != nil {
		return m.CustomerAddress
	}
	return ""
}

func (m *Customer) GetCustomerEmail() string {
	if m != nil {
		return m.CustomerEmail
	}
	return ""
}

func (m *Customer) GetCustomerPhone() string {
	if m != nil {
		return m.CustomerPhone
	}
	return ""
}

type CreateCustomerRequest struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_212f321a2ac7b5a3, []int{1}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type CreateCustomerResponse struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_212f321a2ac7b5a3, []int{2}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto.RegisterType((*Customer)(nil), "customerpb.Customer")
	proto.RegisterType((*CreateCustomerRequest)(nil), "customerpb.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "customerpb.CreateCustomerResponse")
}

func init() { proto.RegisterFile("api/v1/customerpb/customer.proto", fileDescriptor_212f321a2ac7b5a3) }

var fileDescriptor_212f321a2ac7b5a3 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd1, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0x3a, 0xdd, 0x98, 0x4f, 0x9d, 0x12, 0x54, 0x72, 0x2c, 0x15, 0x61, 0x5e, 0x5a,
	0x7f, 0x80, 0x20, 0x5e, 0x74, 0xc5, 0x83, 0x1e, 0x44, 0x7a, 0xf4, 0x32, 0x5e, 0x9b, 0xc7, 0x16,
	0x5c, 0x9b, 0xd8, 0xa4, 0xfb, 0x6f, 0xfd, 0x5f, 0x64, 0xd5, 0xa4, 0x54, 0x4f, 0xde, 0x5e, 0xbe,
	0xf9, 0xf0, 0xc2, 0xcb, 0x83, 0x10, 0xb5, 0x4c, 0xd6, 0x97, 0x49, 0xd1, 0x18, 0xab, 0x4a, 0xaa,
	0x75, 0xee, 0xcb, 0x58, 0xd7, 0xca, 0x2a, 0x06, 0xdd, 0x55, 0xf4, 0x19, 0xc0, 0x38, 0xfd, 0x39,
	0xb2, 0x09, 0x0c, 0xa4, 0xe0, 0x41, 0x18, 0x4c, 0x87, 0xd9, 0x40, 0x0a, 0x76, 0x0a, 0xfb, 0x8e,
	0xce, 0x0b, 0x25, 0x88, 0x0f, 0xc2, 0x60, 0xba, 0x93, 0xed, 0xb9, 0x30, 0x55, 0x82, 0x7a, 0xa8,
	0xc2, 0x92, 0xf8, 0x56, 0x1f, 0xbd, 0x60, 0x49, 0xec, 0x1c, 0x0e, 0x3d, 0x42, 0x21, 0x6a, 0x32,
	0x86, 0x6f, 0xb7, 0xee, 0xc0, 0xe5, 0x0f, 0xdf, 0x31, 0x3b, 0x83, 0x89, 0xa7, 0x54, 0xa2, 0x5c,
	0xf1, 0x61, 0x0b, 0xfd, 0x2b, 0x8f, 0x9b, 0xb0, 0xc7, 0xf4, 0x52, 0x55, 0xc4, 0x47, 0x7d, 0xf6,
	0xba, 0x09, 0xa3, 0x27, 0x38, 0x4e, 0x6b, 0x42, 0x4b, 0x6e, 0xc8, 0x8c, 0x3e, 0x1a, 0x32, 0x96,
	0x5d, 0xc0, 0xd8, 0xc9, 0x76, 0xe2, 0xdd, 0xab, 0xa3, 0xb8, 0xfb, 0x97, 0xd8, 0x73, 0xaf, 0xa2,
	0x67, 0x38, 0xf9, 0xdd, 0xca, 0x68, 0x55, 0x19, 0xfa, 0x7f, 0xaf, 0xd9, 0xec, 0xed, 0x7e, 0x21,
	0xed, 0xb2, 0xc9, 0xe3, 0x42, 0x95, 0xc9, 0x3b, 0xae, 0xf4, 0xe2, 0xe6, 0x36, 0x11, 0x68, 0x31,
	0x47, 0x43, 0x73, 0x43, 0xf5, 0x5a, 0x16, 0x94, 0xfc, 0x59, 0xe5, 0x5d, 0x57, 0xe6, 0xa3, 0x76,
	0x9b, 0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x01, 0xea, 0xcf, 0xbe, 0xf1, 0x01, 0x00, 0x00,
}
